// Mocks generated by Mockito 5.4.6 from annotations
// in nepse_client/test/unit/services/nepse_dashboard_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:nepse_client/src/models/app_settings.dart' as _i2;
import 'package:nepse_client/src/models/dashboard_snapshot.dart' as _i3;
import 'package:nepse_client/src/models/portfolio_holding.dart' as _i5;
import 'package:nepse_client/src/models/portfolio_overview.dart' as _i4;
import 'package:nepse_client/src/models/price_snapshot.dart' as _i7;
import 'package:nepse_client/src/models/watchlist_item.dart' as _i6;
import 'package:nepse_client/src/nepse_api_client.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAppSettings_0 extends _i1.SmartFake implements _i2.AppSettings {
  _FakeAppSettings_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDashboardSnapshot_1 extends _i1.SmartFake
    implements _i3.DashboardSnapshot {
  _FakeDashboardSnapshot_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePortfolioOverview_2 extends _i1.SmartFake
    implements _i4.PortfolioOverview {
  _FakePortfolioOverview_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePortfolioHolding_3 extends _i1.SmartFake
    implements _i5.PortfolioHolding {
  _FakePortfolioHolding_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWatchlistItem_4 extends _i1.SmartFake implements _i6.WatchlistItem {
  _FakeWatchlistItem_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePriceSnapshot_5 extends _i1.SmartFake implements _i7.PriceSnapshot {
  _FakePriceSnapshot_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NepseApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockNepseApiClient extends _i1.Mock implements _i8.NepseApiClient {
  MockNepseApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  void setAuthToken(String? token) => super.noSuchMethod(
    Invocation.method(#setAuthToken, [token]),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<Map<String, dynamic>> login(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i10.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Future<Map<String, dynamic>> getHealth() =>
      (super.noSuchMethod(
            Invocation.method(#getHealth, []),
            returnValue: _i10.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Future<_i2.AppSettings> getSettings() =>
      (super.noSuchMethod(
            Invocation.method(#getSettings, []),
            returnValue: _i10.Future<_i2.AppSettings>.value(
              _FakeAppSettings_0(this, Invocation.method(#getSettings, [])),
            ),
          )
          as _i10.Future<_i2.AppSettings>);

  @override
  _i10.Future<_i2.AppSettings> updateSettings(Map<String, dynamic>? changes) =>
      (super.noSuchMethod(
            Invocation.method(#updateSettings, [changes]),
            returnValue: _i10.Future<_i2.AppSettings>.value(
              _FakeAppSettings_0(
                this,
                Invocation.method(#updateSettings, [changes]),
              ),
            ),
          )
          as _i10.Future<_i2.AppSettings>);

  @override
  _i10.Future<_i3.DashboardSnapshot> getDashboard({int? limit = 5}) =>
      (super.noSuchMethod(
            Invocation.method(#getDashboard, [], {#limit: limit}),
            returnValue: _i10.Future<_i3.DashboardSnapshot>.value(
              _FakeDashboardSnapshot_1(
                this,
                Invocation.method(#getDashboard, [], {#limit: limit}),
              ),
            ),
          )
          as _i10.Future<_i3.DashboardSnapshot>);

  @override
  _i10.Future<_i4.PortfolioOverview> getPortfolio() =>
      (super.noSuchMethod(
            Invocation.method(#getPortfolio, []),
            returnValue: _i10.Future<_i4.PortfolioOverview>.value(
              _FakePortfolioOverview_2(
                this,
                Invocation.method(#getPortfolio, []),
              ),
            ),
          )
          as _i10.Future<_i4.PortfolioOverview>);

  @override
  _i10.Future<_i5.PortfolioHolding> upsertHolding({
    required String? symbol,
    required double? shares,
    required double? buyPrice,
    double? currentPrice,
    String? notes,
    DateTime? lastUpdated,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#upsertHolding, [], {
              #symbol: symbol,
              #shares: shares,
              #buyPrice: buyPrice,
              #currentPrice: currentPrice,
              #notes: notes,
              #lastUpdated: lastUpdated,
            }),
            returnValue: _i10.Future<_i5.PortfolioHolding>.value(
              _FakePortfolioHolding_3(
                this,
                Invocation.method(#upsertHolding, [], {
                  #symbol: symbol,
                  #shares: shares,
                  #buyPrice: buyPrice,
                  #currentPrice: currentPrice,
                  #notes: notes,
                  #lastUpdated: lastUpdated,
                }),
              ),
            ),
          )
          as _i10.Future<_i5.PortfolioHolding>);

  @override
  _i10.Future<void> deleteHolding(String? symbol) =>
      (super.noSuchMethod(
            Invocation.method(#deleteHolding, [symbol]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<List<_i6.WatchlistItem>> getWatchlist() =>
      (super.noSuchMethod(
            Invocation.method(#getWatchlist, []),
            returnValue: _i10.Future<List<_i6.WatchlistItem>>.value(
              <_i6.WatchlistItem>[],
            ),
          )
          as _i10.Future<List<_i6.WatchlistItem>>);

  @override
  _i10.Future<_i6.WatchlistItem> addWatchlistItem(
    String? symbol, {
    String? notes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addWatchlistItem, [symbol], {#notes: notes}),
            returnValue: _i10.Future<_i6.WatchlistItem>.value(
              _FakeWatchlistItem_4(
                this,
                Invocation.method(#addWatchlistItem, [symbol], {#notes: notes}),
              ),
            ),
          )
          as _i10.Future<_i6.WatchlistItem>);

  @override
  _i10.Future<void> removeWatchlistItem(String? symbol) =>
      (super.noSuchMethod(
            Invocation.method(#removeWatchlistItem, [symbol]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<List<_i7.PriceSnapshot>> getPriceSnapshots(
    String? symbol, {
    int? limit = 30,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPriceSnapshots, [symbol], {#limit: limit}),
            returnValue: _i10.Future<List<_i7.PriceSnapshot>>.value(
              <_i7.PriceSnapshot>[],
            ),
          )
          as _i10.Future<List<_i7.PriceSnapshot>>);

  @override
  _i10.Future<_i7.PriceSnapshot> upsertPriceSnapshot({
    required String? symbol,
    required DateTime? tradeDate,
    required double? open,
    required double? high,
    required double? low,
    required double? close,
    double? volume = 0.0,
    String? source = 'manual',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#upsertPriceSnapshot, [], {
              #symbol: symbol,
              #tradeDate: tradeDate,
              #open: open,
              #high: high,
              #low: low,
              #close: close,
              #volume: volume,
              #source: source,
            }),
            returnValue: _i10.Future<_i7.PriceSnapshot>.value(
              _FakePriceSnapshot_5(
                this,
                Invocation.method(#upsertPriceSnapshot, [], {
                  #symbol: symbol,
                  #tradeDate: tradeDate,
                  #open: open,
                  #high: high,
                  #low: low,
                  #close: close,
                  #volume: volume,
                  #source: source,
                }),
              ),
            ),
          )
          as _i10.Future<_i7.PriceSnapshot>);

  @override
  void close() => super.noSuchMethod(
    Invocation.method(#close, []),
    returnValueForMissingStub: null,
  );
}
